#!/bin/sh
#
# $Id: Xreset 189 2005-06-11 00:04:27Z branden $
#
# This script is run as root after the user's X session ends.

PATH="$PATH:/usr/bin/X11"

# Remove the utmp entry for the session.
if grep -qs '^use-sessreg' /etc/X11/xdm/xdm.options \
  && which sessreg >/dev/null 2>&1; then
    sessreg -d -l "$DISPLAY" -u /var/run/utmp -x /etc/X11/xdm/Xservers "$USER"
fi

exit 0

# vim:set ai et sts=4 sw=4 tw=80:
